version: "3"

services:
  nginx:
    image: nginx:1.15-alpine
    network_mode: "host"
    restart: unless-stopped
    volumes:
      - "./data/nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "./data/nginx/general.conf:/etc/nginx/general.conf:ro"
      - "./data/nginx/security.conf:/etc/nginx/security.conf:ro"
      - "./data/nginx/proxy.conf:/etc/nginx/proxy.conf:ro"
      - "./data/nginx/site:/etc/nginx/site"

      - ./data/html:/var/www/html
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
