version: "3.7"
services:
  db:
    image: "mysql"
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=123456
    ports:
      - "3306:3306"
    volumes:
      - ../data/mysql:/var/lib/mysql

networks:
  default:
    name: wp-networks
